name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt-get install
      run: sudo apt-get install gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib make dfu-util
    - name: make
      run: cd usb-hid && make
    - name: Archive dfu file
      uses: actions/upload-artifact@v4
      with:
        name: usb-hid.dfu
        path: usb-hid/usb-hid.dfu
        
